version: '3'

services:
  client:
    build: ./client
    volumes:
    - ./:/var/www
    - /var/www/client/node_modules
    environment:
    - ENV=${ENV:-production}
    command: ./bin/run.sh

  server:
    build: ./server
    volumes:
    - ./:/var/www
    - /var/www/server/node_modules
    environment:
    - ENV=${ENV:-production}
    command: ./bin/run.sh

  mysql:
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
    - MYSQL_HOST=${DB_HOST:-127.0.0.1}
    - MYSQL_DATABASE=${DB_DATABASE:-space_ships}
    - MYSQL_USER=${DB_USER:-space_ships}
    - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-secret}
    ports:
    - 33306:3306

  nginx:
    image: 'nginx:latest'
    volumes:
    - ./var/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - .:/var/www
    ports:
    - 8080:80
    depends_on:
    - mysql
    - client
    - server
